type Experience {
  description: String!
  logo: String!
  order: Int!
  time: String!
  title: String!
  tags: [String!]
}

type User {
  email: String! @unique
}

type Query {
  allExperiences: [Experience!]
}
